# Generated by Django 5.2.8 on 2025-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='password',
            field=models.IntegerField(default=1234, max_length=8),
        ),
    ]
