# Generated by Django 5.2.8 on 2025-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0002_developers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='password',
            field=models.CharField(default=1234, max_length=8),
        ),
    ]
