# Generated by Django 5.2.8 on 2025-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hash_app', '0004_alter_developers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
    ]
